changelog:
  categories:
    - Features:
      labels:
        - "major features"
        - "minor features"
        - "maintain dependencies"
    - Experimental Features:
      labels:
        - experimental
    - Bug Fixes:
      labels:
        - bug
        - bugfix
    - Security:
      labels:
        - security
    - Documentation:
      labels:
        - docs
    - Other Changes:
      labels:
        - "*"
  exclude:
    labels:
      - "ignore for release"
      - contributing
      - "continuous integration"
